# Generated by Django 3.2 on 2021-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ps4Games',
            fields=[
                ('game_name', models.TextField(primary_key=True, serialize=False)),
                ('game_image_link', models.TextField(blank=True, null=True)),
                ('game_guide_url', models.TextField(blank=True, null=True)),
                ('gold', models.TextField(blank=True, db_column='GOLD', null=True)),
                ('silver', models.TextField(blank=True, db_column='SILVER', null=True)),
                ('bronze', models.TextField(blank=True, db_column='BRONZE', null=True)),
                ('platinum', models.TextField(blank=True, db_column='PLATINUM', null=True)),
            ],
            options={
                'db_table': 'PS4_Games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ps4GamesGuide',
            fields=[
                ('game_name', models.TextField(blank=True, null=True)),
                ('trophy_name', models.TextField(primary_key=True, serialize=False)),
                ('trophy_image', models.TextField(blank=True, null=True)),
                ('trophy_type', models.TextField(blank=True, null=True)),
                ('trophy_description', models.TextField(blank=True, null=True)),
                ('trophy_guide', models.TextField(blank=True, null=True)),
                ('youtube_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PS4_Games_Guide',
                'managed': False,
            },
        ),
    ]
