# Generated by Django 3.2 on 2021-05-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PS4Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=500)),
                ('game_image_link', models.CharField(max_length=500)),
                ('game_guide_url', models.CharField(max_length=500)),
                ('GOLD', models.IntegerField()),
                ('SILVER', models.IntegerField()),
                ('BRONZE', models.IntegerField()),
                ('PLATINUM', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PS4GamesGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_name', models.CharField(max_length=500)),
                ('trophy_image', models.CharField(max_length=500)),
                ('trophy_type', models.CharField(max_length=500)),
                ('trophy_description', models.CharField(max_length=500)),
                ('trophy_guide', models.CharField(max_length=500)),
                ('youtube_link', models.CharField(max_length=500, null=True)),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ps4game')),
            ],
        ),
    ]
