# Generated by Django 3.2 on 2021-05-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ps4game',
            options={'ordering': ['id'], 'verbose_name': 'PS4 Game', 'verbose_name_plural': 'PS4 Games'},
        ),
        migrations.AlterModelOptions(
            name='ps4gamesguide',
            options={'ordering': ['id'], 'verbose_name': 'PS4 Guide', 'verbose_name_plural': 'PS4 Guides'},
        ),
        migrations.RenameField(
            model_name='ps4game',
            old_name='BRONZE',
            new_name='bronze',
        ),
        migrations.RenameField(
            model_name='ps4game',
            old_name='GOLD',
            new_name='gold',
        ),
        migrations.RenameField(
            model_name='ps4game',
            old_name='PLATINUM',
            new_name='platinum',
        ),
        migrations.RenameField(
            model_name='ps4game',
            old_name='SILVER',
            new_name='silver',
        ),
    ]
