# Generated by Django 3.2 on 2021-05-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ps4games',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ps4gamesguide',
            options={},
        ),
    ]
