# Generated by Django 3.2 on 2021-05-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210503_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PS4Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=500)),
                ('game_image_link', models.CharField(max_length=500)),
                ('game_guide_url', models.CharField(max_length=500)),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('platinum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'PS4 Game',
                'verbose_name_plural': 'PS4 Games',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Ps4Games',
        ),
        migrations.AlterModelOptions(
            name='ps4gamesguide',
            options={'ordering': ['id'], 'verbose_name': 'PS4 Guide', 'verbose_name_plural': 'PS4 Guides'},
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='trophy_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='trophy_guide',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='trophy_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='trophy_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='trophy_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='youtube_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='ps4gamesguide',
            table=None,
        ),
        migrations.AlterField(
            model_name='ps4gamesguide',
            name='game_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ps4game'),
        ),
    ]
